"""empty message

Revision ID: 4d3cb47aca4f
Revises: 561bdceb1936
Create Date: 2026-01-02 16:32:21.872493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d3cb47aca4f'
down_revision: Union[str, Sequence[str], None] = '561bdceb1936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_info', sa.Column('bought', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_info', 'bought')
    # ### end Alembic commands ###
